<script setup>
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {api} from '../services/api'
import {useEventStore} from '../stores/event'
const events=useEventStore(),rows=ref([]),attendees=ref([]),show=ref(false),busy=ref(false),error=ref(''),uploading=ref(false)
const eventId=computed(()=>events.currentId)
const form=reactive({attendee_id:'',type:'Media',quota_pool:'',valid_from:'',valid_until:'',notes:'',documents:[]})
async function load(){if(!events.loaded)await events.load();if(!eventId.value){rows.value=[];attendees.value=[];return};try{[rows.value,attendees.value]=await Promise.all([api.accreditation(eventId.value),api.attendees(eventId.value)])}catch(e){error.value=e.message}}
onMounted(load);watch(eventId,load)
const name=id=>attendees.value.find(x=>x.id===id)?.name||id
async function create(){busy.value=true;error.value='';try{const row=await api.createAccreditation({...form,event_id:eventId.value});rows.value.unshift(row);show.value=false;Object.assign(form,{attendee_id:'',type:'Media',quota_pool:'',valid_from:'',valid_until:'',notes:'',documents:[]})}catch(e){error.value=e.message}finally{busy.value=false}}
async function setStatus(row,status){try{Object.assign(row,await api.updateAccreditation(row.id,{status}))}catch(e){error.value=e.message}}
async function uploadDoc(file){if(!file)return;uploading.value=true;try{const media=await api.uploadMedia(eventId.value,file,'accreditation_document',false);form.documents.push(media.id)}catch(e){error.value=e.message}finally{uploading.value=false}}
</script>
<template><div class="space-y-6">
<section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Accreditation</p><h1 class="page-title">Verification & Activation</h1><p class="page-subtitle">{{events.current?.name||'Select an event'}} · document review, quota pools, validity and onsite activation.</p></div><button class="btn-primary" :disabled="!eventId||!attendees.length" @click="show=true">+ New Accreditation</button></section>
<p v-if="error" class="rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{{error}}</p>
<section class="grid gap-4 sm:grid-cols-4"><article v-for="[label,statuses] in [['Submitted',['submitted','reviewing']],['Approved',['approved']],['Activated',['activated']],['Blocked',['blocked','rejected','expired']]]" :key="label" class="panel p-5"><p class="panel-kicker">{{label}}</p><p class="mt-2 text-2xl font-black">{{rows.filter(x=>statuses.includes(x.status)).length}}</p></article></section>
<section class="panel overflow-hidden"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Attendee</th><th>Type</th><th>Quota</th><th>Validity</th><th>Docs</th><th>Status</th><th>Action</th></tr></thead><tbody><tr v-if="!rows.length"><td colspan="7" class="text-center">No accreditation records yet.</td></tr><tr v-for="r in rows" :key="r.id"><td><b>{{name(r.attendee_id)}}</b><p class="font-mono">{{r.attendee_id}}</p></td><td>{{r.type}}</td><td>{{r.quota_pool||'—'}}</td><td>{{r.valid_from||'—'}} → {{r.valid_until||'—'}}</td><td><div v-if="r.documents?.length" class="flex flex-wrap gap-1"><a v-for="(doc,i) in r.documents" :key="doc" :href="api.mediaUrl(doc)" target="_blank" rel="noopener" class="btn-secondary py-1 text-[10px]">Doc {{i+1}} ↗</a></div><span v-else>0</span></td><td><span class="status-badge" :class="r.status==='activated'?'badge-published':r.status==='blocked'||r.status==='rejected'?'bg-rose-100 text-rose-700':'badge-draft'">{{r.status}}</span></td><td><div class="flex flex-wrap gap-1"><button v-if="r.status==='submitted'" class="btn-secondary py-1" @click="setStatus(r,'reviewing')">Review</button><button v-if="['submitted','reviewing'].includes(r.status)" class="btn-secondary py-1" @click="setStatus(r,'approved')">Approve</button><button v-if="r.status==='approved'" class="btn-primary py-1" @click="setStatus(r,'activated')">Activate</button><button v-if="!['blocked','rejected'].includes(r.status)" class="btn-secondary py-1 text-rose-600" @click="setStatus(r,'blocked')">Block</button></div></td></tr></tbody></table></div></section>
<div v-if="show" class="modal-backdrop" @click.self="show=false"><form class="modal-card max-h-[90vh] overflow-y-auto" @submit.prevent="create"><h2 class="text-lg font-bold">New accreditation</h2><div class="mt-5 grid gap-4"><label class="field"><span>Attendee</span><select v-model="form.attendee_id" required><option value="">Select attendee</option><option v-for="a in attendees" :key="a.id" :value="a.id">{{a.name}} · {{a.category}}</option></select></label><div class="grid grid-cols-2 gap-3"><label class="field"><span>Type</span><select v-model="form.type"><option>Media</option><option>Staff</option><option>Speaker</option><option>VIP</option><option>Vendor</option><option>Security</option></select></label><label class="field"><span>Quota pool</span><input v-model="form.quota_pool"/></label></div><div class="grid grid-cols-2 gap-3"><label class="field"><span>Valid from</span><input v-model="form.valid_from" type="date"/></label><label class="field"><span>Valid until</span><input v-model="form.valid_until" type="date"/></label></div><label class="field"><span>Document</span><input type="file" accept=".pdf,image/*" @change="uploadDoc($event.target.files?.[0])"/><small>{{uploading?'Uploading…':form.documents.length+' file(s) attached'}}</small></label><label class="field"><span>Notes</span><textarea v-model="form.notes" rows="3"></textarea></label></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="show=false">Cancel</button><button class="btn-primary" :disabled="busy||uploading">Create</button></div></form></div>
</div></template>
