<script setup>
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {api} from '../services/api'
import {useEventStore} from '../stores/event'
import QrCredential from '../components/QrCredential.vue'

const events=useEventStore(),rows=ref([]),schema=ref(null),q=ref(''),category=ref('All'),status=ref('All'),showAdd=ref(false),showImport=ref(false),credential=ref(null),csv=ref(''),error=ref('')
const eventId=computed(()=>events.currentId)
const form=reactive({name:'',email:'',phone:'',company:'',category:'General',status:'Pending'})
const categories=computed(()=>['All',...(schema.value?.categories||['General'])])
const statuses=['All','Confirmed','Pending','Waitlist','Rejected']

async function load(){
  error.value=''
  if(!events.loaded)await events.load()
  if(!eventId.value){rows.value=[];schema.value=null;return}
  try{[rows.value,schema.value]=await Promise.all([api.attendees(eventId.value),api.registration(eventId.value)]);form.category=schema.value.categories?.[0]||'General'}catch(e){error.value=e.message}
}
onMounted(load);watch(eventId,load)
const filtered=computed(()=>rows.value.filter(x=>(category.value==='All'||x.category===category.value)&&(status.value==='All'||x.status===status.value)&&(String(x.name||'')+String(x.company||'')+String(x.id||'')+String(x.email||'')).toLowerCase().includes(q.value.toLowerCase())))
async function add(){error.value='';try{const row=await api.createAttendee({...form,event_id:eventId.value});rows.value.unshift(row);showAdd.value=false;Object.assign(form,{name:'',email:'',phone:'',company:'',category:schema.value?.categories?.[0]||'General',status:'Pending'})}catch(e){error.value=e.message}}
async function setStatus(row,next){try{Object.assign(row,await api.updateAttendee(row.id,{status:next}))}catch(e){error.value=e.message}}
async function importCsv(){try{await api.importAttendees(csv.value,eventId.value);showImport.value=false;csv.value='';await load()}catch(e){error.value=e.message}}
async function showCredential(row){try{credential.value=await api.credential(row.id)}catch(e){error.value=e.message}}
function exportCsv(){window.location.assign(api.attendeeExportUrl(eventId.value))}
</script>
<template><div class="space-y-6">
<section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">People</p><h1 class="page-title">Attendees <span class="text-slate-400">({{rows.length}})</span></h1><p class="page-subtitle">{{events.current?.name||'Select an event'}} · approvals, import/export and signed credentials.</p></div><div class="flex flex-wrap gap-2"><button class="btn-secondary" :disabled="!eventId" @click="showImport=true">Import CSV</button><button class="btn-secondary" :disabled="!eventId" @click="exportCsv">Export CSV</button><button class="btn-primary" :disabled="!eventId" @click="showAdd=true">+ Add Attendee</button></div></section>
<p v-if="error" class="rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{{error}}</p>
<section class="panel overflow-hidden"><div class="grid gap-3 border-b border-slate-100 p-4 sm:grid-cols-[1fr_160px_160px]"><input v-model="q" class="control" placeholder="Search by name, email, ticket ID…"/><select v-model="category" class="control"><option v-for="c in categories" :key="c">{{c}}</option></select><select v-model="status" class="control"><option v-for="s in statuses" :key="s">{{s}}</option></select></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Name</th><th>Category</th><th>Company</th><th>Registration ID</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-if="!filtered.length"><td colspan="6" class="text-center">{{eventId?'No attendees yet.':'Create or select an event.'}}</td></tr><tr v-for="r in filtered" :key="r.id"><td><div class="flex items-center gap-3"><div class="grid h-9 w-9 place-items-center rounded-full bg-indigo-50 text-xs font-bold text-indigo-700">{{r.initials}}</div><div><b>{{r.name}}</b><p>{{r.email}}</p></div></div></td><td><span class="soft-pill">{{r.category}}</span></td><td>{{r.company||'—'}}</td><td class="font-mono text-xs">{{r.id}}</td><td><span class="status-badge" :class="r.status==='Confirmed'?'badge-published':'badge-draft'">{{r.status}}</span></td><td><div class="flex gap-1"><button v-if="r.status!=='Confirmed'" class="icon-btn" title="Approve" @click="setStatus(r,'Confirmed')">✓</button><button v-if="r.status==='Pending'" class="icon-btn" title="Reject" @click="setStatus(r,'Rejected')">×</button><button class="icon-btn" title="QR credential" @click="showCredential(r)">▦</button></div></td></tr></tbody></table></div></section>
<div v-if="showAdd" class="modal-backdrop" @click.self="showAdd=false"><form class="modal-card" @submit.prevent="add"><h2 class="text-lg font-bold">Add attendee</h2><div class="mt-5 grid gap-4"><label class="field"><span>Name</span><input v-model="form.name" required/></label><label class="field"><span>Email</span><input v-model="form.email" type="email" required/></label><label class="field"><span>Phone</span><input v-model="form.phone"/></label><label class="field"><span>Company</span><input v-model="form.company"/></label><label class="field"><span>Category</span><select v-model="form.category"><option v-for="c in schema?.categories||['General']" :key="c">{{c}}</option></select></label><label class="field"><span>Status</span><select v-model="form.status"><option>Pending</option><option>Confirmed</option><option>Waitlist</option></select></label></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="showAdd=false">Cancel</button><button class="btn-primary">Create</button></div></form></div>
<div v-if="showImport" class="modal-backdrop" @click.self="showImport=false"><div class="modal-card"><h2 class="text-lg font-bold">Import attendees</h2><p class="mt-2 text-xs text-slate-500">CSV rows are assigned to <b>{{events.current?.name}}</b>. Headers: name,email,phone,company,category,status.</p><textarea v-model="csv" class="control mt-4 min-h-48 font-mono text-xs" placeholder="name,email,company,category&#10;Jane Doe,jane@example.com,Acme,VIP"></textarea><div class="mt-6 flex justify-end gap-2"><button class="btn-secondary" @click="showImport=false">Cancel</button><button class="btn-primary" @click="importCsv">Import</button></div></div></div>
<div v-if="credential" class="modal-backdrop" @click.self="credential=null"><div class="modal-card"><p class="panel-kicker">Signed QR credential</p><h2 class="mt-2 text-lg font-bold">{{credential.attendee_id}}</h2><QrCredential :value="credential.payload" class="mt-4"/><p class="mt-3 break-all rounded-xl bg-slate-950 p-3 font-mono text-[9px] leading-4 text-cyan-200">{{credential.payload}}</p><button class="btn-secondary mt-5 w-full" @click="credential=null">Close</button></div></div>
</div></template>
