<script setup>
import {computed,onMounted,ref} from 'vue'
import {api} from '../services/api'
const rows=ref([]),q=ref(''),category=ref('All')
onMounted(async()=>rows.value=await api.attendees())
const filtered=computed(()=>rows.value.filter(x=>(category.value==='All'||x.category===category.value)&&(x.name+x.company+x.id).toLowerCase().includes(q.value.toLowerCase())))
const categories=['All','General','VIP','Sponsor','Speaker','Media']
</script>
<template><div class="space-y-6"><section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">People</p><h1 class="page-title">Attendees <span class="text-slate-400">(18,442)</span></h1><p class="page-subtitle">Search, segment and operate the attendee directory.</p></div><div class="flex gap-2"><button class="btn-secondary">Export</button><button class="btn-primary">+ Add Attendee</button></div></section><section class="panel overflow-hidden"><div class="grid gap-3 border-b border-slate-100 p-4 sm:grid-cols-[1fr_180px_180px]"><input v-model="q" class="control" placeholder="Search by name, email, ticket ID…"/><select v-model="category" class="control"><option v-for="c in categories" :key="c">{{c}}</option></select><select class="control"><option>All Status</option><option>Confirmed</option><option>Pending</option></select></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Name</th><th>Category</th><th>Company</th><th>Ticket ID</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="r in filtered" :key="r.id"><td><div class="flex items-center gap-3"><div class="grid h-9 w-9 place-items-center rounded-full bg-indigo-50 text-xs font-bold text-indigo-700">{{r.initials}}</div><div><b>{{r.name}}</b><p>{{r.email}}</p></div></div></td><td><span class="soft-pill">{{r.category}}</span></td><td>{{r.company}}</td><td class="font-mono text-xs">{{r.id}}</td><td><span class="status-badge" :class="r.status==='Confirmed'?'badge-published':'badge-draft'">{{r.status}}</span></td><td><button class="icon-btn">⋮</button></td></tr></tbody></table></div></section></div></template>
