<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useEventStore } from '../stores/event'
import { api } from '../services/api'
import QrCredential from '../components/QrCredential.vue'

const events=useEventStore(),rows=ref([]),selected=ref(null),show=ref(false),showPrint=ref(false),busy=ref(false),prints=ref([]),attendees=ref([]),error=ref('')
const eventId=computed(()=>events.currentId)
const form=reactive({event_id:'',name:'VIP Badge',width_mm:100,height_mm:140,background:'#ffffff',accent:'#4f46e5',show_qr:true,fields:['name','company','category'],category:'VIP'})
const printForm=reactive({event_id:'',attendee_id:'',template_id:'',copies:1})
async function load(){if(!events.loaded)await events.load();if(!eventId.value){rows.value=[];prints.value=[];selected.value=null;return};[rows.value,prints.value,attendees.value]=await Promise.all([api.badges(eventId.value),api.badgePrints(eventId.value),api.attendees(eventId.value)]);selected.value=rows.value[0]||null}
onMounted(load);watch(eventId,load)
const previewStyle=computed(()=>({background:selected.value?.background||'#fff',borderColor:selected.value?.accent||'#4f46e5'}))
async function create(){busy.value=true;error.value='';try{form.event_id=eventId.value;const row=await api.createBadge(form);rows.value.unshift(row);selected.value=row;show.value=false}catch(e){error.value=e.message}finally{busy.value=false}}
async function save(){if(!selected.value)return;const row=await api.updateBadge(selected.value.id,selected.value);Object.assign(selected.value,row)}
async function queuePrint(){try{printForm.event_id=eventId.value;printForm.template_id=selected.value?.id||'';const job=await api.createBadgePrint(printForm);prints.value.unshift(job);showPrint.value=false}catch(e){error.value=e.message}}
function printBadge(){window.print()}
</script>
<template><div class="space-y-6">
<section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Badges</p><h1 class="page-title">Badge Designer</h1><p class="page-subtitle">{{events.current?.name||'Select an event'}} · templates, QR placement and print queue.</p></div><div class="flex gap-2"><button class="btn-secondary" :disabled="!eventId||!selected" @click="showPrint=true">+ Print Job</button><button class="btn-primary" :disabled="!eventId" @click="show=true">+ New Template</button></div></section>
<p v-if="error" class="rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{{error}}</p>
<section class="grid gap-5 xl:grid-cols-[280px_1fr_360px]">
<aside class="panel overflow-hidden"><div class="border-b p-4"><p class="panel-kicker">Templates</p></div><button v-for="r in rows" :key="r.id" @click="selected=r" class="w-full border-b border-slate-100 p-4 text-left hover:bg-slate-50" :class="selected?.id===r.id?'bg-indigo-50':''"><b class="text-sm">{{r.name}}</b><p class="mt-1 text-xs text-slate-400">{{r.category}} · {{r.width_mm}}×{{r.height_mm}} mm</p></button></aside>
<article v-if="selected" class="panel p-6"><div class="flex justify-between gap-3"><div><p class="panel-kicker">Template settings</p><h2 class="panel-title">{{selected.name}}</h2></div><button class="btn-primary" @click="save">Save</button></div><div class="mt-6 grid gap-5 sm:grid-cols-2"><label class="field sm:col-span-2"><span>Name</span><input v-model="selected.name"/></label><label class="field"><span>Category</span><input v-model="selected.category"/></label><label class="field"><span>Accent</span><input v-model="selected.accent" type="color" class="h-11"/></label><label class="field"><span>Width (mm)</span><input v-model.number="selected.width_mm" type="number"/></label><label class="field"><span>Height (mm)</span><input v-model.number="selected.height_mm" type="number"/></label><label class="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-sm font-bold sm:col-span-2">Show QR <input v-model="selected.show_qr" type="checkbox" class="accent-indigo-600"/></label></div></article>
<aside class="panel p-6"><div class="flex items-center justify-between"><p class="panel-kicker">Sample preview</p><button class="btn-secondary py-1.5 no-print" @click="printBadge">Print</button></div><div class="badge-print mx-auto mt-5 flex aspect-[5/7] max-w-[260px] flex-col overflow-hidden rounded-2xl border-4 bg-white shadow-xl" :style="previewStyle"><div class="h-20 p-4 text-white" :style="{background:selected?.accent||'#4f46e5'}"><p class="text-xs font-black">{{events.current?.branding?.brand_name||events.current?.name||'EVENT'}}</p><p class="mt-1 text-[10px] opacity-80">{{events.current?.name||'Selected event'}}</p></div><div class="flex flex-1 flex-col items-center p-5 text-center"><div class="grid h-16 w-16 place-items-center rounded-full bg-slate-100 text-xl font-black">SA</div><h3 class="mt-4 text-xl font-black">Sample Attendee</h3><p class="mt-1 text-sm text-slate-500">Sample Company</p><span class="mt-3 rounded-full px-3 py-1 text-xs font-black text-white" :style="{background:selected?.accent||'#4f46e5'}">{{selected?.category||'GENERAL'}}</span><QrCredential v-if="selected?.show_qr" class="mt-auto scale-75" value="digisangam://credential/preview-badge"/></div></div></aside>
</section>
<section class="panel overflow-hidden"><div class="border-b p-4"><p class="panel-kicker">Production queue</p><h2 class="panel-title">Badge print jobs</h2></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Job</th><th>Attendee</th><th>Template</th><th>Provider</th><th>Copies</th><th>Status</th></tr></thead><tbody><tr v-if="!prints.length"><td colspan="6" class="text-center">No print jobs queued.</td></tr><tr v-for="p in prints" :key="p.id"><td class="font-mono">{{p.id}}</td><td class="font-mono">{{p.attendee_id}}</td><td>{{rows.find(x=>x.id===p.template_id)?.name||p.template_id}}</td><td>{{p.provider||'server default'}}</td><td>{{p.copies}}</td><td><span class="status-badge badge-draft">{{p.status}}</span></td></tr></tbody></table></div></section>
<div v-if="showPrint" class="modal-backdrop" @click.self="showPrint=false"><form class="modal-card" @submit.prevent="queuePrint"><h2 class="text-lg font-bold">Queue badge print</h2><div class="mt-5 grid gap-4"><label class="field"><span>Attendee</span><select v-model="printForm.attendee_id" required><option value="">Select attendee</option><option v-for="a in attendees" :key="a.id" :value="a.id">{{a.name}} · {{a.category}}</option></select></label><label class="field"><span>Copies</span><input v-model.number="printForm.copies" type="number" min="1" max="10"/></label><p class="rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">Printer routing is server-controlled through the active log, raw TCP or CUPS provider. This job will use that configured provider.</p></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="showPrint=false">Cancel</button><button class="btn-primary">Queue</button></div></form></div>
<div v-if="show" class="modal-backdrop" @click.self="show=false"><form class="modal-card" @submit.prevent="create"><h2 class="text-lg font-bold">New badge template</h2><div class="mt-5 grid gap-4"><label class="field"><span>Name</span><input v-model="form.name"/></label><label class="field"><span>Category</span><input v-model="form.category"/></label></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="show=false">Cancel</button><button class="btn-primary" :disabled="busy">Create</button></div></form></div>
</div></template>
