<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { api } from '../services/api'
import QrCredential from '../components/QrCredential.vue'

const rows=ref([]),selected=ref(null),show=ref(false),busy=ref(false)
const form=reactive({event_id:'evt_001',name:'VIP Badge',width_mm:100,height_mm:140,background:'#ffffff',accent:'#4f46e5',show_qr:true,fields:['name','company','category'],category:'VIP'})
onMounted(async()=>{rows.value=await api.badges();selected.value=rows.value[0]||null})
const previewStyle=computed(()=>({background:selected.value?.background||'#fff',borderColor:selected.value?.accent||'#4f46e5'}))
async function create(){busy.value=true;try{const row=await api.createBadge(form);rows.value.unshift(row);selected.value=row;show.value=false}finally{busy.value=false}}
async function save(){if(!selected.value)return;const row=await api.updateBadge(selected.value.id,selected.value);Object.assign(selected.value,row)}
function printBadge(){window.print()}
</script>
<template><div class="space-y-6">
<section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Badges</p><h1 class="page-title">Badge Designer</h1><p class="page-subtitle">Category-aware badge templates with dynamic attendee fields and QR placement.</p></div><button class="btn-primary" @click="show=true">+ New Template</button></section>
<section class="grid gap-5 xl:grid-cols-[280px_1fr_360px]">
<aside class="panel overflow-hidden"><div class="border-b p-4"><p class="panel-kicker">Templates</p></div><button v-for="r in rows" :key="r.id" @click="selected=r" class="w-full border-b border-slate-100 p-4 text-left hover:bg-slate-50" :class="selected?.id===r.id?'bg-indigo-50':''"><b class="text-sm">{{r.name}}</b><p class="mt-1 text-xs text-slate-400">{{r.category}} · {{r.width_mm}}×{{r.height_mm}} mm</p></button></aside>
<article v-if="selected" class="panel p-6"><div class="flex justify-between gap-3"><div><p class="panel-kicker">Template settings</p><h2 class="panel-title">{{selected.name}}</h2></div><button class="btn-primary" @click="save">Save</button></div><div class="mt-6 grid gap-5 sm:grid-cols-2"><label class="field sm:col-span-2"><span>Name</span><input v-model="selected.name"/></label><label class="field"><span>Category</span><input v-model="selected.category"/></label><label class="field"><span>Accent</span><input v-model="selected.accent" type="color" class="h-11"/></label><label class="field"><span>Width (mm)</span><input v-model.number="selected.width_mm" type="number"/></label><label class="field"><span>Height (mm)</span><input v-model.number="selected.height_mm" type="number"/></label><label class="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-sm font-bold sm:col-span-2">Show QR <input v-model="selected.show_qr" type="checkbox" class="accent-indigo-600"/></label></div></article>
<aside class="panel p-6"><div class="flex items-center justify-between"><p class="panel-kicker">Live preview</p><button class="btn-secondary py-1.5 no-print" @click="printBadge">Print</button></div><div class="badge-print mx-auto mt-5 flex aspect-[5/7] max-w-[260px] flex-col overflow-hidden rounded-2xl border-4 bg-white shadow-xl" :style="previewStyle"><div class="h-20 p-4 text-white" :style="{background:selected?.accent||'#4f46e5'}"><p class="text-xs font-black">DIGISANGAM</p><p class="mt-1 text-[10px] opacity-80">Tech & Innovation Summit</p></div><div class="flex flex-1 flex-col items-center p-5 text-center"><div class="grid h-16 w-16 place-items-center rounded-full bg-slate-100 text-xl font-black">AS</div><h3 class="mt-4 text-xl font-black">Aarav Sharma</h3><p class="mt-1 text-sm text-slate-500">Indigiti</p><span class="mt-3 rounded-full px-3 py-1 text-xs font-black text-white" :style="{background:selected?.accent||'#4f46e5'}">{{selected?.category||'GENERAL'}}</span><QrCredential v-if="selected?.show_qr" class="mt-auto scale-75" value="digisangam://credential/preview-badge"/></div></div></aside>
</section>
<div v-if="show" class="modal-backdrop" @click.self="show=false"><form class="modal-card" @submit.prevent="create"><h2 class="text-lg font-bold">New badge template</h2><div class="mt-5 grid gap-4"><label class="field"><span>Name</span><input v-model="form.name"/></label><label class="field"><span>Category</span><input v-model="form.category"/></label></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="show=false">Cancel</button><button class="btn-primary" :disabled="busy">Create</button></div></form></div>
</div></template>
