<script setup>
import {onMounted,ref} from 'vue'
import {api} from '../services/api'
import StatCard from '../components/StatCard.vue'
import LineSpark from '../components/LineSpark.vue'
const data=ref(null)
onMounted(async()=>{data.value=await api.dashboard()})
</script>
<template><div v-if="data" class="space-y-6">
<section class="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p class="eyebrow">Command Center</p><h1 class="page-title">Welcome back, John</h1><p class="page-subtitle">Here’s what’s happening across your events today.</p></div><div class="flex gap-2"><button class="btn-secondary">Export</button><RouterLink to="/events/create" class="btn-primary">+ Create Event</RouterLink></div></section>
<section class="panel overflow-hidden p-0"><div class="grid gap-0 lg:grid-cols-[1.6fr_.8fr]"><div class="p-5 sm:p-6"><div class="flex items-center justify-between gap-4"><div class="flex items-center gap-4"><div class="grid h-20 w-28 place-items-center rounded-2xl bg-gradient-to-br from-indigo-600 via-violet-500 to-cyan-400 text-sm font-bold text-white">LIVE EVENT</div><div><div class="mb-1 inline-flex rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-700">{{data.event.status}}</div><h2 class="text-lg font-bold">{{data.event.name}}</h2><p class="mt-1 text-sm text-slate-500">{{data.event.date}} · {{data.event.location}}</p></div></div><RouterLink to="/events" class="btn-secondary hidden sm:inline-flex">Manage</RouterLink></div></div><div class="border-t border-slate-200 bg-slate-50/60 p-5 lg:border-l lg:border-t-0"><p class="text-xs font-bold uppercase tracking-widest text-slate-400">Event health</p><div class="mt-3 flex items-center gap-3"><div class="h-2 flex-1 rounded-full bg-slate-200"><div class="h-full w-[88%] rounded-full bg-emerald-500"></div></div><b class="text-sm">88%</b></div><p class="mt-2 text-xs text-slate-500">Registration velocity and operational readiness are healthy.</p></div></div></section>
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard v-for="s in data.stats" :key="s.label" v-bind="s"/></section>
<section class="grid gap-5 xl:grid-cols-[1.55fr_.75fr]"><article class="panel p-5 sm:p-6"><div class="flex items-center justify-between"><div><p class="panel-kicker">Registrations</p><h2 class="panel-title">Registration trend</h2></div><select class="select-sm"><option>This month</option></select></div><LineSpark :values="data.trend"/><div class="mt-1 grid grid-cols-6 text-center text-[10px] font-medium text-slate-400"><span>Oct 1</span><span>5</span><span>10</span><span>15</span><span>20</span><span>31</span></div></article>
<article class="panel p-5 sm:p-6"><p class="panel-kicker">Audience</p><h2 class="panel-title">Attendee categories</h2><div class="mt-6 flex items-center gap-5"><div class="donut" :style="{background:'conic-gradient('+data.categories.map((c,i)=>c.color+' '+data.categories.slice(0,i).reduce((a,x)=>a+x.value,0)+'% '+data.categories.slice(0,i+1).reduce((a,x)=>a+x.value,0)+'%').join(',')+')'}"><div>18.4k<br><span>Total</span></div></div><div class="min-w-0 flex-1 space-y-2"><div v-for="c in data.categories" :key="c.label" class="flex items-center justify-between text-xs"><span class="flex items-center gap-2 text-slate-600"><i class="h-2 w-2 rounded-full" :style="{background:c.color}"></i>{{c.label}}</span><b>{{c.value}}%</b></div></div></div></article></section>
</div><div v-else class="panel h-96 animate-pulse"></div></template>
