<script setup>
import {onMounted,reactive,ref} from 'vue'
import {useRoute} from 'vue-router'
import {api} from '../services/api'
import {useEventStore} from '../stores/event'

const route=useRoute(),events=useEventStore(),busy=ref(false),saved=ref(false),loading=ref(true),error=ref('')
const form=reactive({id:'',name:'',description:'',type:'Conference',category:'Business',format:'in_person',start_date:'',end_date:'',timezone:'Asia/Kolkata',location:'',venue_name:'',website:'',currency:'INR',privacy:'public',status:'Draft',branding:{},organizer:{},public_page:{}})

onMounted(async()=>{try{const data=await api.event(route.params.id);Object.assign(form,data);form.branding={primary_color:'#4f46e5',secondary_color:'#06b6d4',background_color:'#0f172a',brand_name:'',logo_url:'',cover_url:'',...(data.branding||{})};form.organizer={name:'',email:'',phone:'',...(data.organizer||{})};form.public_page={headline:'',show_location:true,show_organizer:true,...(data.public_page||{})};events.select(data.id)}catch(e){error.value=e.message}finally{loading.value=false}})
async function save(){busy.value=true;saved.value=false;error.value='';try{Object.assign(form,await api.updateEvent(form.id,form));saved.value=true;await events.load()}catch(e){error.value=e.message}finally{busy.value=false}}
</script>
<template><div v-if="!loading" class="space-y-6">
<section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Event workspace</p><h1 class="page-title">{{form.name}}</h1><p class="page-subtitle">{{form.start_date||'Date not set'}} · {{form.location||'Location not set'}}</p></div><div class="flex flex-wrap gap-2"><RouterLink :to="'/events/'+form.id+'/preview'" class="btn-secondary">Preview</RouterLink><RouterLink v-if="['Published','Live'].includes(form.status)" :to="'/e/'+form.id" class="btn-secondary">View Public Page ↗</RouterLink><RouterLink to="/registrations" class="btn-secondary">Registration</RouterLink><RouterLink to="/tickets" class="btn-secondary">Tickets</RouterLink><button class="btn-primary" :disabled="busy" @click="save">{{busy?'Saving…':'Save Event'}}</button></div></section>
<p v-if="error" class="rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{{error}}</p>
<section class="grid gap-4 sm:grid-cols-4"><article class="panel p-5"><p class="panel-kicker">Status</p><div class="mt-3"><span class="status-badge" :class="form.status==='Live'?'badge-live':form.status==='Published'?'badge-published':'badge-draft'">{{form.status}}</span></div></article><article class="panel p-5"><p class="panel-kicker">Registrations</p><p class="mt-2 text-2xl font-black">{{form.registrations||0}}</p></article><article class="panel p-5"><p class="panel-kicker">Setup</p><p class="mt-2 text-2xl font-black">{{form.progress||0}}%</p></article><article class="panel p-5"><p class="panel-kicker">Public route</p><p class="mt-2 truncate font-mono text-xs font-bold">/e/{{form.id}}</p></article></section>

<section class="grid gap-5 xl:grid-cols-[1fr_.85fr]">
<form class="panel p-6" @submit.prevent="save"><h2 class="text-lg font-bold">Core settings</h2><div class="mt-6 grid gap-5 md:grid-cols-2"><label class="field md:col-span-2"><span>Event name</span><input v-model="form.name" required/></label><label class="field md:col-span-2"><span>Description</span><textarea v-model="form.description" rows="4"></textarea></label><label class="field"><span>Type</span><input v-model="form.type"/></label><label class="field"><span>Category</span><input v-model="form.category"/></label><label class="field"><span>Format</span><select v-model="form.format"><option value="in_person">In person</option><option value="hybrid">Hybrid</option><option value="virtual">Virtual</option></select></label><label class="field"><span>Status</span><select v-model="form.status"><option>Draft</option><option>Published</option><option>Live</option><option>Completed</option><option>Archived</option></select></label><label class="field"><span>Start date</span><input v-model="form.start_date" type="date"/></label><label class="field"><span>End date</span><input v-model="form.end_date" type="date"/></label><label class="field"><span>Venue</span><input v-model="form.venue_name"/></label><label class="field"><span>Location</span><input v-model="form.location"/></label><label class="field"><span>Timezone</span><input v-model="form.timezone"/></label><label class="field"><span>Currency</span><input v-model="form.currency"/></label><label class="field"><span>Privacy</span><select v-model="form.privacy"><option value="public">Public</option><option value="private">Private</option><option value="invite_only">Invite only</option></select></label><label class="field"><span>Website</span><input v-model="form.website"/></label></div></form>

<div class="space-y-5">
<form class="panel p-6" @submit.prevent="save"><p class="panel-kicker">Branding</p><h2 class="panel-title">Public identity</h2><div class="mt-5 grid gap-4"><label class="field"><span>Brand name</span><input v-model="form.branding.brand_name"/></label><label class="field"><span>Logo URL</span><input v-model="form.branding.logo_url" placeholder="https://…"/></label><label class="field"><span>Cover image URL</span><input v-model="form.branding.cover_url" placeholder="https://…"/></label><div class="grid grid-cols-3 gap-3"><label class="field"><span>Primary</span><input v-model="form.branding.primary_color" type="color" class="h-11"/></label><label class="field"><span>Accent</span><input v-model="form.branding.secondary_color" type="color" class="h-11"/></label><label class="field"><span>Hero</span><input v-model="form.branding.background_color" type="color" class="h-11"/></label></div><label class="field"><span>Hero headline</span><input v-model="form.public_page.headline"/></label></div></form>
<form class="panel p-6" @submit.prevent="save"><p class="panel-kicker">Organizer</p><div class="mt-4 grid gap-4"><label class="field"><span>Name</span><input v-model="form.organizer.name"/></label><label class="field"><span>Email</span><input v-model="form.organizer.email" type="email"/></label><label class="field"><span>Phone</span><input v-model="form.organizer.phone"/></label></div></form>
</div>
</section>
<div class="flex items-center justify-end gap-3"><span v-if="saved" class="text-xs font-bold text-emerald-600">Saved</span><button class="btn-primary" :disabled="busy" @click="save">Save all event settings</button></div>
</div><div v-else class="panel h-96 animate-pulse"></div></template>
