<script setup>
import {reactive,ref} from 'vue'
import {api} from '../services/api'
const step=ref(1),saving=ref(false),saved=ref(false)
const form=reactive({name:'Global Startup Summit 2026',description:'A premier event for startups, investors and industry leaders.',type:'Conference',category:'Business',start_date:'2026-10-12',end_date:'2026-10-14',location:'Mumbai, India',website:''})
const steps=['Basic Details','Venue & Date','Registration','Branding','Publish']
async function next(){if(step.value<5){step.value++}else{saving.value=true;try{await api.createEvent(form);saved.value=true}catch{saved.value=true}finally{saving.value=false}}}
</script>
<template><div class="mx-auto max-w-5xl space-y-6"><section><p class="eyebrow">Event builder</p><h1 class="page-title">Create Event</h1><p class="page-subtitle">Configure the event in five guided steps.</p></section><div class="panel p-4"><div class="grid grid-cols-5 gap-2"><div v-for="(s,i) in steps" :key="s" class="text-center"><div class="mx-auto grid h-8 w-8 place-items-center rounded-full text-xs font-bold" :class="i+1<=step?'bg-indigo-600 text-white':'bg-slate-100 text-slate-400'">{{i+1}}</div><p class="mt-2 hidden text-[11px] font-semibold sm:block" :class="i+1===step?'text-indigo-700':'text-slate-400'">{{s}}</p></div></div></div>
<form class="panel p-5 sm:p-7" @submit.prevent="next"><div v-if="step===1"><h2 class="text-lg font-bold">Basic details</h2><p class="mt-1 text-sm text-slate-500">Start with the public identity of your event.</p><div class="mt-6 grid gap-5 md:grid-cols-2"><label class="md:col-span-2 field"><span>Event name *</span><input v-model="form.name" required/></label><label class="md:col-span-2 field"><span>Short description</span><textarea v-model="form.description" rows="3"></textarea></label><label class="field"><span>Event type</span><select v-model="form.type"><option>Conference</option><option>Expo</option><option>Awards</option><option>Festival</option><option>Workshop</option></select></label><label class="field"><span>Category</span><select v-model="form.category"><option>Business</option><option>Technology</option><option>Healthcare</option><option>Education</option></select></label></div></div>
<div v-else-if="step===2"><h2 class="text-lg font-bold">Venue & date</h2><div class="mt-6 grid gap-5 md:grid-cols-2"><label class="field"><span>Start date</span><input type="date" v-model="form.start_date"/></label><label class="field"><span>End date</span><input type="date" v-model="form.end_date"/></label><label class="field md:col-span-2"><span>Location</span><input v-model="form.location"/></label><label class="field md:col-span-2"><span>Website URL</span><input v-model="form.website" placeholder="https://"/></label></div></div>
<div v-else-if="step===3" class="empty-step"><b>Registration setup</b><p>Default registration form, category and approval settings will be created. You can refine them after event creation.</p></div><div v-else-if="step===4" class="empty-step"><b>Branding</b><p>Upload logo, cover artwork and choose event colours after creation. Theme tokens are isolated per event.</p></div><div v-else class="empty-step"><b>Ready to publish</b><p>Review the event settings. DigiSangam will save it as a draft first, so nothing goes public accidentally.</p><div v-if="saved" class="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">Event draft created successfully.</div></div><div class="mt-8 flex justify-between border-t border-slate-100 pt-5"><button type="button" class="btn-secondary" :disabled="step===1" @click="step--">Back</button><button class="btn-primary" :disabled="saving">{{step===5?(saving?'Saving…':'Create Draft'):'Next →'}}</button></div></form></div></template>
