<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { api } from '../services/api'
const route=useRoute(),busy=ref(false),saved=ref(false),loading=ref(true)
const form=reactive({id:'',name:'',description:'',type:'Conference',category:'Business',start_date:'',end_date:'',location:'',website:'',status:'Draft',registrations:'0'})
onMounted(async()=>{const data=await api.event(route.params.id);Object.assign(form,data);loading.value=false})
async function save(){busy.value=true;saved.value=false;try{Object.assign(form,await api.updateEvent(form.id,form));saved.value=true}finally{busy.value=false}}
</script>
<template><div v-if="!loading" class="space-y-6">
<section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Event workspace</p><h1 class="page-title">{{form.name}}</h1><p class="page-subtitle">{{form.start_date||form.date}} · {{form.location}}</p></div><div class="flex flex-wrap gap-2"><a v-if="['Published','Live'].includes(form.status)" :href="'/e/'+form.id" target="_blank" rel="noopener" class="btn-secondary">View Public Page ↗</a><RouterLink to="/registrations" class="btn-secondary">Registration</RouterLink><RouterLink to="/tickets" class="btn-secondary">Tickets</RouterLink><button class="btn-primary" :disabled="busy" @click="save">{{busy?'Saving…':'Save Event'}}</button></div></section>
<section class="grid gap-4 sm:grid-cols-3"><article class="panel p-5"><p class="panel-kicker">Status</p><div class="mt-3"><span class="status-badge" :class="form.status==='Live'?'badge-live':form.status==='Published'?'badge-published':'badge-draft'">{{form.status}}</span></div></article><article class="panel p-5"><p class="panel-kicker">Registrations</p><p class="mt-2 text-2xl font-black">{{form.registrations||0}}</p></article><article class="panel p-5"><p class="panel-kicker">Public URL</p><p class="mt-2 truncate font-mono text-xs font-bold">/e/{{form.id}}</p></article></section>
<form class="panel p-6" @submit.prevent="save"><div class="flex items-center justify-between"><div><h2 class="text-lg font-bold">Event settings</h2><p class="mt-1 text-sm text-slate-500">Core public details and lifecycle status.</p></div><span v-if="saved" class="text-xs font-bold text-emerald-600">Saved</span></div><div class="mt-6 grid gap-5 md:grid-cols-2"><label class="field md:col-span-2"><span>Event name</span><input v-model="form.name" required/></label><label class="field md:col-span-2"><span>Description</span><textarea v-model="form.description" rows="4"></textarea></label><label class="field"><span>Type</span><select v-model="form.type"><option>Conference</option><option>Expo</option><option>Awards</option><option>Festival</option><option>Workshop</option></select></label><label class="field"><span>Status</span><select v-model="form.status"><option>Draft</option><option>Published</option><option>Live</option><option>Completed</option><option>Archived</option></select></label><label class="field"><span>Start date</span><input v-model="form.start_date" type="date"/></label><label class="field"><span>End date</span><input v-model="form.end_date" type="date"/></label><label class="field md:col-span-2"><span>Location</span><input v-model="form.location"/></label><label class="field md:col-span-2"><span>Website</span><input v-model="form.website" placeholder="https://"/></label></div><div class="mt-6 flex justify-end"><button class="btn-primary" :disabled="busy">Save changes</button></div></form>
</div><div v-else class="panel h-96 animate-pulse"></div></template>
