<script setup>
import {onMounted,ref} from 'vue'
import {api} from '../services/api'
const rows=ref([]),active=ref('All Events')
const tabs=['All Events','Upcoming','Live','Past','Draft']
onMounted(async()=>{rows.value=await api.events()})
const statusClass=s=>({Live:'badge-live',Published:'badge-published',Draft:'badge-draft'}[s]||'badge-draft')
</script>
<template><div class="space-y-6"><section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Event portfolio</p><h1 class="page-title">Events</h1><p class="page-subtitle">Create, publish and operate every event from one place.</p></div><RouterLink to="/events/create" class="btn-primary">+ Create Event</RouterLink></section><section class="panel overflow-hidden"><div class="flex flex-wrap gap-1 border-b border-slate-200 px-4 pt-3"><button v-for="tab in tabs" :key="tab" @click="active=tab" class="tab-btn" :class="{active:active===tab}">{{tab}}</button></div><div class="divide-y divide-slate-100"><div v-for="row in rows" :key="row.id" class="grid gap-4 px-4 py-4 sm:grid-cols-[1fr_auto] sm:items-center lg:grid-cols-[1.4fr_.7fr_.5fr_.6fr_auto]"><div class="flex items-center gap-3"><div class="h-14 w-20 rounded-xl bg-gradient-to-br from-indigo-500 to-cyan-400"></div><div><h3 class="text-sm font-bold">{{row.name}}</h3><p class="mt-1 text-xs text-slate-500">{{row.date}} · {{row.location}}</p></div></div><span :class="statusClass(row.status)" class="status-badge">{{row.status}}</span><div><p class="text-sm font-bold">{{row.registrations}}</p><p class="text-[11px] text-slate-400">Registrations</p></div><div class="hidden lg:block"><div class="mb-1 flex justify-between text-[10px] text-slate-400"><span>Setup</span><span>{{row.progress}}%</span></div><div class="h-1.5 w-28 rounded-full bg-slate-100"><div class="h-full rounded-full bg-indigo-500" :style="{width:row.progress+'%'}"></div></div></div><button class="btn-secondary">Manage</button></div></div></section></div></template>
