<script setup>
import {reactive,ref} from 'vue'
import {useRouter} from 'vue-router'
import {api} from '../services/api'
import {useEventStore} from '../stores/event'
const router=useRouter(),events=useEventStore(),prompt=ref(''),blueprint=ref(null),busy=ref(false),error=ref('')
const edits=reactive({})
async function generate(){busy.value=true;error.value='';try{blueprint.value=await api.eventBlueprint(prompt.value);Object.assign(edits,JSON.parse(JSON.stringify(blueprint.value)))}catch(e){error.value=e.message}finally{busy.value=false}}
async function create(){busy.value=true;error.value='';try{const event=await api.createEvent(edits);events.add(event);router.push('/events/'+event.id)}catch(e){error.value=e.message}finally{busy.value=false}}
</script>
<template><div class="mx-auto max-w-5xl space-y-6"><section><p class="eyebrow">AI Event Builder</p><h1 class="page-title">Describe the event. Start with a blueprint.</h1><p class="page-subtitle">DigiSangam turns your brief into an editable event, registration, ticket and branding configuration. Nothing is created until you approve it.</p></section><section class="panel p-6"><textarea v-model="prompt" class="control min-h-36" placeholder="Create a two-day hybrid technology conference in Pune for general attendees, VIPs, speakers and sponsors with manual approval…"></textarea><div class="mt-4 flex justify-end"><button class="btn-primary" :disabled="busy||!prompt.trim()" @click="generate">{{busy?'Generating…':'Generate Blueprint'}}</button></div></section><p v-if="error" class="rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{{error}}</p><section v-if="blueprint" class="grid gap-5 xl:grid-cols-[1fr_.8fr]"><article class="panel p-6"><p class="panel-kicker">Editable blueprint</p><div class="mt-5 grid gap-4"><label class="field"><span>Event name</span><input v-model="edits.name"/></label><label class="field"><span>Description</span><textarea v-model="edits.description" rows="4"></textarea></label><div class="grid grid-cols-2 gap-3"><label class="field"><span>Type</span><input v-model="edits.type"/></label><label class="field"><span>Format</span><select v-model="edits.format"><option value="in_person">In person</option><option value="hybrid">Hybrid</option><option value="virtual">Virtual</option></select></label></div><label class="field"><span>Registration categories</span><input :value="edits.registration.categories.join(', ')" @input="edits.registration.categories=$event.target.value.split(',').map(x=>x.trim()).filter(Boolean)"/></label><div class="grid grid-cols-2 gap-3"><label class="field"><span>Ticket name</span><input v-model="edits.ticket.name"/></label><label class="field"><span>Capacity</span><input v-model.number="edits.ticket.quantity" type="number"/></label></div></div><button class="btn-primary mt-6 w-full" :disabled="busy" @click="create">Approve Blueprint & Create Draft</button></article><aside class="panel p-6"><p class="panel-kicker">Why this configuration</p><div class="mt-4 space-y-3"><p v-for="x in blueprint.explanation" :key="x" class="rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{{x}}</p></div><div class="mt-5 rounded-2xl p-5 text-white" :style="{background:'linear-gradient(135deg,'+edits.branding.primary_color+','+edits.branding.secondary_color+')'}"><p class="text-xs font-black uppercase tracking-widest opacity-70">Brand preview</p><h3 class="mt-2 text-xl font-black">{{edits.branding.brand_name}}</h3></div></aside></section></div></template>
