<script setup>
import {computed,onMounted,ref} from 'vue'
import {api} from '../services/api'
import {useEventStore} from '../stores/event'
const eventStore=useEventStore(),rows=ref([]),active=ref('All')
const tabs=['All','Draft','Published','Live','Completed','Archived']
onMounted(async()=>{rows.value=await api.events();eventStore.events=rows.value})
const statusClass=s=>({Live:'badge-live',Published:'badge-published',Draft:'badge-draft',Completed:'bg-slate-100 text-slate-600',Archived:'bg-slate-100 text-slate-400'}[s]||'badge-draft')
const visible=computed(()=>active.value==='All'?rows.value:rows.value.filter(r=>r.status===active.value))
</script>
<template><div class="space-y-6"><section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Event portfolio</p><h1 class="page-title">Events</h1><p class="page-subtitle">Only real stored events are shown here—no demo records.</p></div><RouterLink to="/events/create" class="btn-primary">+ Create Event</RouterLink></section>
<section class="panel overflow-hidden"><div class="flex flex-wrap gap-1 border-b border-slate-200 px-4 pt-3"><button v-for="tab in tabs" :key="tab" @click="active=tab" class="tab-btn" :class="{active:active===tab}">{{tab}}</button></div><div v-if="!visible.length" class="p-12 text-center"><h3 class="font-black">No {{active==='All'?'events':active.toLowerCase()+' events'}}</h3><p class="mt-2 text-sm text-slate-500">Create an event to start configuring registration, tickets, branding and operations.</p></div><div v-else class="divide-y divide-slate-100"><div v-for="row in visible" :key="row.id" class="grid gap-4 px-4 py-4 sm:grid-cols-[1fr_auto] sm:items-center lg:grid-cols-[1.4fr_.7fr_.5fr_.6fr_auto]"><div class="flex items-center gap-3"><img v-if="row.branding?.cover_url" :src="row.branding.cover_url" class="h-14 w-20 rounded-xl object-cover"/><div v-else class="h-14 w-20 rounded-xl" :style="{background:`linear-gradient(135deg,${row.branding?.primary_color||'#4f46e5'},${row.branding?.secondary_color||'#06b6d4'})`}"></div><div><h3 class="text-sm font-bold">{{row.name}}</h3><p class="mt-1 text-xs text-slate-500">{{row.start_date||'Date not set'}} · {{row.location||'Location not set'}}</p></div></div><span :class="statusClass(row.status)" class="status-badge">{{row.status}}</span><div><p class="text-sm font-bold">{{row.registrations||0}}</p><p class="text-[11px] text-slate-400">Registrations</p></div><div class="hidden lg:block"><div class="mb-1 flex justify-between text-[10px] text-slate-400"><span>Setup</span><span>{{row.progress||0}}%</span></div><div class="h-1.5 w-28 rounded-full bg-slate-100"><div class="h-full rounded-full bg-indigo-500" :style="{width:(row.progress||0)+'%'}"></div></div></div><RouterLink :to="'/events/'+row.id" class="btn-secondary">Manage</RouterLink></div></div></section></div></template>
