<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useEventStore } from '../stores/event'
import { api } from '../services/api'
const events=useEventStore(),rows=ref([]),leads=ref([]),meetings=ref([]),attendees=ref([]),show=ref(false),showLead=ref(false),showMeeting=ref(false),busy=ref(false),q=ref(''),tab=ref('companies'),error=ref('')
const eventId=computed(()=>events.currentId)
const form=reactive({event_id:'',name:'',type:'Exhibitor',booth:'',contact_name:'',contact_email:'',staff_quota:5,lead_quota:250,status:'active'})
const lead=reactive({event_id:'',exhibitor_id:'',attendee_id:'',score:60,intent:'warm',notes:'',owner:''})
const meeting=reactive({event_id:'',exhibitor_id:'',attendee_id:'',start_at:'',duration_minutes:30,location:'Meeting Lounge',status:'scheduled'})
function seedMeetingTime(){const day=events.current?.start_date||'';meeting.start_at=day?day+'T14:00':''}
async function load(){
  error.value=''
  if(!events.loaded)await events.load()
  if(!eventId.value){rows.value=[];leads.value=[];meetings.value=[];attendees.value=[];seedMeetingTime();return}
  try{[rows.value,leads.value,meetings.value,attendees.value]=await Promise.all([api.exhibitors(eventId.value),api.leads(eventId.value),api.meetings(eventId.value),api.attendees(eventId.value)]);seedMeetingTime()}
  catch(e){error.value=e.message}
}
onMounted(load);watch(eventId,load)
const filtered=computed(()=>rows.value.filter(x=>(x.name+x.booth+x.type).toLowerCase().includes(q.value.toLowerCase())))
const sponsors=computed(()=>rows.value.filter(x=>x.type==='Sponsor').length)
const companyName=id=>rows.value.find(x=>x.id===id)?.name||id
async function create(){busy.value=true;error.value='';try{form.event_id=eventId.value;const row=await api.createExhibitor(form);rows.value.unshift(row);show.value=false}catch(e){error.value=e.message}finally{busy.value=false}}
async function captureLead(){busy.value=true;error.value='';try{lead.event_id=eventId.value;leads.value.unshift(await api.createLead(lead));showLead.value=false;Object.assign(lead,{event_id:'',exhibitor_id:'',attendee_id:'',score:60,intent:'warm',notes:'',owner:''})}catch(e){error.value=e.message}finally{busy.value=false}}
async function bookMeeting(){busy.value=true;error.value='';try{meeting.event_id=eventId.value;meetings.value.unshift(await api.createMeeting(meeting));showMeeting.value=false;Object.assign(meeting,{event_id:'',exhibitor_id:'',attendee_id:'',duration_minutes:30,location:'Meeting Lounge',status:'scheduled'});seedMeetingTime()}catch(e){error.value=e.message}finally{busy.value=false}}
async function toggleCompany(row){try{Object.assign(row,await api.updateExhibitor(row.id,{status:row.status==='active'?'inactive':'active'}))}catch(e){error.value=e.message}}
async function setMeetingStatus(row,status){try{Object.assign(row,await api.updateMeeting(row.id,{status}))}catch(e){error.value=e.message}}
</script>
<template><div class="space-y-6">
<section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Marketplace</p><h1 class="page-title">Exhibitors & Sponsors</h1><p class="page-subtitle">{{events.current?.name||'Select an event'}} · companies, leads and meetings.</p></div><div class="flex flex-wrap gap-2"><button class="btn-secondary" :disabled="!eventId||!rows.length" @click="showLead=true">+ Capture Lead</button><button class="btn-secondary" :disabled="!eventId||!rows.length" @click="showMeeting=true">+ Book Meeting</button><button class="btn-primary" :disabled="!eventId" @click="show=true">+ Add Company</button></div></section>
<p v-if="error" class="rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{{error}}</p>
<section class="grid gap-4 sm:grid-cols-4"><article class="panel p-5"><p class="panel-kicker">Companies</p><p class="mt-2 text-2xl font-black">{{rows.length}}</p></article><article class="panel p-5"><p class="panel-kicker">Sponsors</p><p class="mt-2 text-2xl font-black">{{sponsors}}</p></article><article class="panel p-5"><p class="panel-kicker">Leads</p><p class="mt-2 text-2xl font-black">{{leads.length}}</p></article><article class="panel p-5"><p class="panel-kicker">Meetings</p><p class="mt-2 text-2xl font-black">{{meetings.length}}</p></article></section>
<div class="flex gap-1 border-b border-slate-200"><button v-for="t in ['companies','leads','meetings']" :key="t" class="tab-btn capitalize" :class="{active:tab===t}" @click="tab=t">{{t}}</button></div>
<section v-if="tab==='companies'" class="panel overflow-hidden"><div class="border-b p-4"><input v-model="q" class="control max-w-md" placeholder="Search company or booth…"/></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Company</th><th>Type</th><th>Booth</th><th>Contact</th><th>Staff</th><th>Lead quota</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="r in filtered" :key="r.id"><td><b>{{r.name}}</b></td><td><span class="soft-pill">{{r.type}}</span></td><td class="font-mono">{{r.booth||'—'}}</td><td>{{r.contact_name}}<p>{{r.contact_email}}</p></td><td>{{r.staff_quota}}</td><td>{{r.lead_quota}}</td><td><span class="status-badge" :class="r.status==='active'?'badge-published':'badge-draft'">{{r.status}}</span></td><td><button class="btn-secondary py-1" @click="toggleCompany(r)">{{r.status==='active'?'Disable':'Enable'}}</button></td></tr></tbody></table></div></section>
<section v-else-if="tab==='leads'" class="panel overflow-hidden"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Company</th><th>Attendee</th><th>Intent</th><th>Score</th><th>Owner</th><th>Captured</th></tr></thead><tbody><tr v-if="!leads.length"><td colspan="6" class="text-center">No leads captured yet.</td></tr><tr v-for="r in leads" :key="r.id"><td><b>{{companyName(r.exhibitor_id)}}</b></td><td class="font-mono">{{r.attendee_id}}</td><td><span class="soft-pill">{{r.intent}}</span></td><td>{{r.score}}/100</td><td>{{r.owner||'—'}}</td><td>{{r.created_at?.slice(0,16).replace('T',' ')}}</td></tr></tbody></table></div></section>
<section v-else class="panel overflow-hidden"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Company</th><th>Attendee</th><th>Start</th><th>Duration</th><th>Location</th><th>Status</th></tr></thead><tbody><tr v-if="!meetings.length"><td colspan="6" class="text-center">No meetings booked yet.</td></tr><tr v-for="r in meetings" :key="r.id"><td><b>{{companyName(r.exhibitor_id)}}</b></td><td class="font-mono">{{r.attendee_id}}</td><td>{{r.start_at}}</td><td>{{r.duration_minutes}} min</td><td>{{r.location}}</td><td><select class="control min-w-32 py-1 text-xs" :value="r.status" @change="setMeetingStatus(r,$event.target.value)"><option value="scheduled">scheduled</option><option value="completed">completed</option><option value="cancelled">cancelled</option><option value="no_show">no show</option></select></td></tr></tbody></table></div></section>

<div v-if="show" class="modal-backdrop" @click.self="show=false"><form class="modal-card max-h-[90vh] overflow-y-auto" @submit.prevent="create"><h2 class="text-lg font-bold">Add exhibitor / sponsor</h2><div class="mt-5 grid gap-4"><label class="field"><span>Company</span><input v-model="form.name" required/></label><div class="grid grid-cols-2 gap-3"><label class="field"><span>Type</span><select v-model="form.type"><option>Exhibitor</option><option>Sponsor</option><option>Partner</option></select></label><label class="field"><span>Booth</span><input v-model="form.booth"/></label></div><label class="field"><span>Contact name</span><input v-model="form.contact_name"/></label><label class="field"><span>Contact email</span><input v-model="form.contact_email" type="email"/></label><div class="grid grid-cols-2 gap-3"><label class="field"><span>Staff quota</span><input v-model.number="form.staff_quota" type="number"/></label><label class="field"><span>Lead quota</span><input v-model.number="form.lead_quota" type="number"/></label></div></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="show=false">Cancel</button><button class="btn-primary" :disabled="busy">Add</button></div></form></div>
<div v-if="showLead" class="modal-backdrop" @click.self="showLead=false"><form class="modal-card" @submit.prevent="captureLead"><h2 class="text-lg font-bold">Capture lead</h2><div class="mt-5 grid gap-4"><label class="field"><span>Exhibitor</span><select v-model="lead.exhibitor_id" required><option value="">Select company</option><option v-for="r in rows" :key="r.id" :value="r.id">{{r.name}} · {{r.booth}}</option></select></label><label class="field"><span>Attendee</span><select v-model="lead.attendee_id" required><option value="">Select attendee</option><option v-for="a in attendees" :key="a.id" :value="a.id">{{a.name}} · {{a.category}}</option></select></label><div class="grid grid-cols-2 gap-3"><label class="field"><span>Intent</span><select v-model="lead.intent"><option>hot</option><option>warm</option><option>low</option></select></label><label class="field"><span>Score</span><input v-model.number="lead.score" type="number" min="0" max="100"/></label></div><label class="field"><span>Notes</span><textarea v-model="lead.notes" rows="3"></textarea></label></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="showLead=false">Cancel</button><button class="btn-primary">Save Lead</button></div></form></div>
<div v-if="showMeeting" class="modal-backdrop" @click.self="showMeeting=false"><form class="modal-card" @submit.prevent="bookMeeting"><h2 class="text-lg font-bold">Book meeting</h2><div class="mt-5 grid gap-4"><label class="field"><span>Exhibitor</span><select v-model="meeting.exhibitor_id" required><option value="">Select company</option><option v-for="r in rows" :key="r.id" :value="r.id">{{r.name}}</option></select></label><label class="field"><span>Attendee</span><select v-model="meeting.attendee_id" required><option value="">Select attendee</option><option v-for="a in attendees" :key="a.id" :value="a.id">{{a.name}} · {{a.category}}</option></select></label><label class="field"><span>Starts</span><input v-model="meeting.start_at" type="datetime-local"/></label><div class="grid grid-cols-2 gap-3"><label class="field"><span>Minutes</span><input v-model.number="meeting.duration_minutes" type="number"/></label><label class="field"><span>Location</span><input v-model="meeting.location"/></label></div></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="showMeeting=false">Cancel</button><button class="btn-primary">Book</button></div></form></div>
</div></template>
