<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { api } from '../services/api'
const rows=ref([]),show=ref(false),busy=ref(false),q=ref('')
const form=reactive({event_id:'evt_001',name:'',type:'Exhibitor',booth:'',contact_name:'',contact_email:'',staff_quota:5,lead_quota:250,status:'active'})
onMounted(async()=>rows.value=await api.exhibitors())
const filtered=computed(()=>rows.value.filter(x=>(x.name+x.booth+x.type).toLowerCase().includes(q.value.toLowerCase())))
const sponsors=computed(()=>rows.value.filter(x=>x.type==='Sponsor').length)
async function create(){busy.value=true;try{const row=await api.createExhibitor(form);rows.value.unshift(row);show.value=false}finally{busy.value=false}}
</script>
<template><div class="space-y-6">
<section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Marketplace</p><h1 class="page-title">Exhibitors & Sponsors</h1><p class="page-subtitle">Booths, staff entitlements, sponsor status and lead quotas in one operating view.</p></div><button class="btn-primary" @click="show=true">+ Add Company</button></section>
<section class="grid gap-4 sm:grid-cols-3"><article class="panel p-5"><p class="panel-kicker">Companies</p><p class="mt-2 text-2xl font-black">{{rows.length}}</p></article><article class="panel p-5"><p class="panel-kicker">Sponsors</p><p class="mt-2 text-2xl font-black">{{sponsors}}</p></article><article class="panel p-5"><p class="panel-kicker">Lead capacity</p><p class="mt-2 text-2xl font-black">{{rows.reduce((n,x)=>n+Number(x.lead_quota||0),0)}}</p></article></section>
<section class="panel overflow-hidden"><div class="border-b p-4"><input v-model="q" class="control max-w-md" placeholder="Search company or booth…"/></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Company</th><th>Type</th><th>Booth</th><th>Contact</th><th>Staff</th><th>Lead quota</th><th>Status</th></tr></thead><tbody><tr v-for="r in filtered" :key="r.id"><td><b>{{r.name}}</b></td><td><span class="soft-pill">{{r.type}}</span></td><td class="font-mono">{{r.booth||'—'}}</td><td>{{r.contact_name}}<p>{{r.contact_email}}</p></td><td>{{r.staff_quota}}</td><td>{{r.lead_quota}}</td><td><span class="status-badge badge-published">{{r.status}}</span></td></tr></tbody></table></div></section>
<div v-if="show" class="modal-backdrop" @click.self="show=false"><form class="modal-card max-h-[90vh] overflow-y-auto" @submit.prevent="create"><h2 class="text-lg font-bold">Add exhibitor / sponsor</h2><div class="mt-5 grid gap-4"><label class="field"><span>Company</span><input v-model="form.name" required/></label><div class="grid grid-cols-2 gap-3"><label class="field"><span>Type</span><select v-model="form.type"><option>Exhibitor</option><option>Sponsor</option><option>Partner</option></select></label><label class="field"><span>Booth</span><input v-model="form.booth"/></label></div><label class="field"><span>Contact name</span><input v-model="form.contact_name"/></label><label class="field"><span>Contact email</span><input v-model="form.contact_email" type="email"/></label><div class="grid grid-cols-2 gap-3"><label class="field"><span>Staff quota</span><input v-model.number="form.staff_quota" type="number"/></label><label class="field"><span>Lead quota</span><input v-model.number="form.lead_quota" type="number"/></label></div></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="show=false">Cancel</button><button class="btn-primary" :disabled="busy">Add</button></div></form></div>
</div></template>
