<script setup>
import {ref} from 'vue'
const palette=['Text Field','Email','Phone','Dropdown','Multi Select','Radio Button','Date Picker','File Upload','Paragraph']
const fields=ref([{label:'Full Name',type:'Text Field',required:true},{label:'Email Address',type:'Email',required:true},{label:'Mobile Number',type:'Phone',required:true},{label:'Category',type:'Dropdown',required:true},{label:'Company Name',type:'Text Field',required:false},{label:'Designation',type:'Text Field',required:false}])
const selected=ref(0)
function add(type){fields.value.push({label:type,type,required:false});selected.value=fields.value.length-1}
function remove(){if(fields.value.length){fields.value.splice(selected.value,1);selected.value=Math.max(0,selected.value-1)}}
</script>
<template><div class="space-y-6"><section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Registration</p><h1 class="page-title">Registration Form Builder</h1><p class="page-subtitle">Design forms with reusable fields and conditional rules.</p></div><div class="flex gap-2"><button class="btn-secondary">Preview</button><button class="btn-primary">Save Form</button></div></section><section class="grid min-h-[650px] gap-4 xl:grid-cols-[210px_1fr_300px]"><aside class="panel p-4"><p class="panel-kicker">Add field</p><div class="mt-3 space-y-2"><button v-for="p in palette" :key="p" @click="add(p)" class="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-left text-xs font-semibold hover:border-indigo-300 hover:bg-indigo-50">{{p}}</button></div></aside><article class="panel p-5"><div class="mx-auto max-w-xl"><p class="panel-kicker">Form canvas</p><div class="mt-4 space-y-3"><button v-for="(f,i) in fields" :key="i" @click="selected=i" class="w-full rounded-xl border p-3 text-left transition" :class="selected===i?'border-indigo-500 ring-4 ring-indigo-50':'border-slate-200 hover:border-slate-300'"><div class="flex justify-between"><span class="text-xs font-bold">{{f.label}} <i v-if="f.required" class="text-rose-500">*</i></span><span class="text-[10px] text-slate-400">{{f.type}}</span></div><div class="mt-2 h-9 rounded-lg border border-slate-200 bg-slate-50"></div></button></div></div></article><aside class="panel p-5" v-if="fields[selected]"><p class="panel-kicker">Field settings</p><div class="mt-4 space-y-4"><label class="field"><span>Label</span><input v-model="fields[selected].label"/></label><label class="flex items-center justify-between text-sm font-semibold">Required <input type="checkbox" v-model="fields[selected].required" class="h-4 w-4 accent-indigo-600"/></label><label class="field"><span>Visibility</span><select><option>Always</option><option>Conditional</option></select></label><label class="field"><span>Category rule</span><select><option>All categories</option><option>VIP only</option><option>Speaker only</option></select></label><button @click="remove" class="w-full rounded-xl border border-rose-200 py-2.5 text-xs font-bold text-rose-600 hover:bg-rose-50">Delete field</button></div></aside></section></div></template>
