<script setup>
import { onMounted, reactive, ref } from 'vue'
import { api } from '../services/api'
const rows=ref([]),show=ref(false),busy=ref(false)
const form=reactive({name:'General Admission',price:3999,quantity:500,status:'Active',event_id:'evt_001',sale_start:'',sale_end:''})
onMounted(async()=>rows.value=await api.tickets())
async function add(){busy.value=true;try{const row=await api.createTicket(form);rows.value.unshift(row);show.value=false}finally{busy.value=false}}
async function toggle(row){const updated=await api.updateTicket(row.id,{status:row.status==='Active'?'Paused':'Active'});Object.assign(row,updated)}
const money=n=>n===0?'₹0':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)
</script>
<template><div class="space-y-6"><section class="flex justify-between gap-4"><div><p class="eyebrow">Commerce</p><h1 class="page-title">Ticket Types</h1><p class="page-subtitle">Persistent pricing, capacity, availability and inventory state.</p></div><button class="btn-primary self-end" @click="show=true">+ Add Ticket Type</button></section>
<section class="panel overflow-hidden"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Name</th><th>Price</th><th>Quantity</th><th>Sold</th><th>Utilisation</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td><b>{{r.name}}</b></td><td>{{money(r.price)}}</td><td>{{r.quantity}}</td><td>{{r.sold}}</td><td><div class="flex items-center gap-2"><div class="h-1.5 w-24 rounded-full bg-slate-100"><div class="h-full rounded-full bg-indigo-500" :style="{width:Math.round(r.sold/r.quantity*100)+'%'}"></div></div><small>{{Math.round(r.sold/r.quantity*100)}}%</small></div></td><td><span class="status-badge" :class="r.status==='Active'?'badge-published':'badge-draft'">{{r.status}}</span></td><td><button class="btn-secondary py-1.5" @click="toggle(r)">{{r.status==='Active'?'Pause':'Activate'}}</button></td></tr></tbody></table></div></section>
<div v-if="show" class="modal-backdrop" @click.self="show=false"><form class="modal-card" @submit.prevent="add"><h2 class="text-lg font-bold">Add ticket type</h2><p class="mt-1 text-sm text-slate-500">Create a persistent ticket inventory bucket.</p><div class="mt-5 grid gap-4"><label class="field"><span>Name</span><input v-model="form.name" required/></label><label class="field"><span>Price</span><input v-model.number="form.price" type="number" min="0"/></label><label class="field"><span>Quantity</span><input v-model.number="form.quantity" type="number" min="1"/></label><div class="grid grid-cols-2 gap-3"><label class="field"><span>Sale starts</span><input v-model="form.sale_start" type="date"/></label><label class="field"><span>Sale ends</span><input v-model="form.sale_end" type="date"/></label></div></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="show=false">Cancel</button><button class="btn-primary" :disabled="busy">{{busy?'Saving…':'Add Ticket'}}</button></div></form></div>
</div></template>
