<script setup>
import {onMounted,ref} from 'vue'
import {api} from '../services/api'
const rows=ref([]),show=ref(false)
onMounted(async()=>rows.value=await api.tickets())
function add(){rows.value.unshift({id:'tic_'+Date.now(),name:'New Ticket',price:1999,quantity:100,sold:0,status:'Active'});show.value=false}
const money=n=>n===0?'₹0':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)
</script>
<template><div class="space-y-6"><section class="flex justify-between gap-4"><div><p class="eyebrow">Commerce</p><h1 class="page-title">Ticket Types</h1><p class="page-subtitle">Control pricing, inventory and sale availability.</p></div><button class="btn-primary self-end" @click="show=true">+ Add Ticket Type</button></section><section class="panel overflow-hidden"><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Name</th><th>Price</th><th>Quantity</th><th>Sold</th><th>Utilisation</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td><b>{{r.name}}</b></td><td>{{money(r.price)}}</td><td>{{r.quantity}}</td><td>{{r.sold}}</td><td><div class="flex items-center gap-2"><div class="h-1.5 w-24 rounded-full bg-slate-100"><div class="h-full rounded-full bg-indigo-500" :style="{width:Math.round(r.sold/r.quantity*100)+'%'}"></div></div><small>{{Math.round(r.sold/r.quantity*100)}}%</small></div></td><td><span class="status-badge badge-published">{{r.status}}</span></td><td><button class="icon-btn">⋮</button></td></tr></tbody></table></div></section><div v-if="show" class="modal-backdrop" @click.self="show=false"><div class="modal-card"><h2 class="text-lg font-bold">Add ticket type</h2><p class="mt-1 text-sm text-slate-500">Create a new inventory bucket for this event.</p><div class="mt-5 grid gap-4"><label class="field"><span>Name</span><input value="New Ticket"/></label><label class="field"><span>Price</span><input type="number" value="1999"/></label><label class="field"><span>Quantity</span><input type="number" value="100"/></label></div><div class="mt-6 flex justify-end gap-2"><button class="btn-secondary" @click="show=false">Cancel</button><button class="btn-primary" @click="add">Add Ticket</button></div></div></div></div></template>
