<script setup>
import { onMounted, reactive, ref } from 'vue'
import { api } from '../services/api'
const eventId='evt_001',busy=ref(false),saved=ref(false),showSeat=ref(false),seats=ref([])
const venue=reactive({event_id:eventId,name:'',address:'',zones:[],seating:[]})
const seatForm=reactive({attendee_id:'',hall_id:'',seat:''})
onMounted(async()=>{Object.assign(venue,await api.venue(eventId));seats.value=await api.seatAssignments(eventId)})
function addZone(){venue.zones.push({id:'zone_'+Date.now(),name:'New Zone',capacity:100,categories:['General']})}
function addHall(){venue.seating.push({id:'hall_'+Date.now(),name:'New Hall',type:'general',capacity:100})}
async function save(){busy.value=true;saved.value=false;try{Object.assign(venue,await api.updateVenue(eventId,venue));saved.value=true}finally{busy.value=false}}
async function assignSeat(){busy.value=true;try{seats.value.unshift(await api.assignSeat(eventId,seatForm));showSeat.value=false;Object.assign(seatForm,{attendee_id:'',hall_id:'',seat:''})}finally{busy.value=false}}
</script>
<template><div class="space-y-6">
<section class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow">Venue</p><h1 class="page-title">Zones & Seating</h1><p class="page-subtitle">Model access zones, room capacity and reserved/general seating for onsite rules.</p></div><div class="flex items-center gap-2"><span v-if="saved" class="text-xs font-bold text-emerald-600">Saved</span><button class="btn-secondary" @click="showSeat=true">Assign Seat</button><button class="btn-primary" :disabled="busy" @click="save">Save Venue</button></div></section>
<section class="panel p-6"><div class="grid gap-5 md:grid-cols-2"><label class="field"><span>Venue name</span><input v-model="venue.name"/></label><label class="field"><span>Address</span><input v-model="venue.address"/></label></div></section>
<section class="grid gap-5 xl:grid-cols-2">
<article class="panel p-6"><div class="flex items-center justify-between"><div><p class="panel-kicker">Access control</p><h2 class="panel-title">Zones</h2></div><button class="btn-secondary" @click="addZone">+ Zone</button></div><div class="mt-5 space-y-3"><div v-for="(z,i) in venue.zones" :key="z.id" class="rounded-2xl border border-slate-200 p-4"><div class="grid gap-3 sm:grid-cols-[1fr_100px]"><input v-model="z.name" class="control font-bold"/><input v-model.number="z.capacity" class="control" type="number"/></div><p class="mt-3 text-xs text-slate-400">Allowed categories</p><input class="control mt-1" :value="z.categories?.join(', ')" @change="z.categories=$event.target.value.split(',').map(x=>x.trim()).filter(Boolean)"/><button class="mt-2 text-xs font-bold text-rose-600" @click="venue.zones.splice(i,1)">Remove</button></div></div></article>
<article class="panel p-6"><div class="flex items-center justify-between"><div><p class="panel-kicker">Capacity planning</p><h2 class="panel-title">Rooms & Seating</h2></div><button class="btn-secondary" @click="addHall">+ Hall</button></div><div class="mt-5 space-y-3"><div v-for="(h,i) in venue.seating" :key="h.id" class="rounded-2xl border border-slate-200 p-4"><div class="grid gap-3 sm:grid-cols-2"><input v-model="h.name" class="control font-bold"/><select v-model="h.type" class="control"><option value="general">General admission</option><option value="reserved">Reserved seating</option></select></div><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="field" v-if="h.type==='general'"><span>Capacity</span><input v-model.number="h.capacity" type="number"/></label><template v-else><label class="field"><span>Rows</span><input v-model.number="h.rows" type="number"/></label><label class="field"><span>Seats / row</span><input v-model.number="h.seats_per_row" type="number"/></label></template></div><button class="mt-2 text-xs font-bold text-rose-600" @click="venue.seating.splice(i,1)">Remove</button></div></div></article>
</section>
<section class="panel overflow-hidden"><div class="border-b p-4"><p class="panel-kicker">Reserved seating</p><h2 class="panel-title">Seat assignments</h2></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Attendee</th><th>Hall</th><th>Seat</th><th>Assigned</th></tr></thead><tbody><tr v-if="!seats.length"><td colspan="4" class="text-center">No seats assigned.</td></tr><tr v-for="s in seats" :key="s.id"><td class="font-mono">{{s.attendee_id}}</td><td>{{venue.seating.find(x=>x.id===s.hall_id)?.name||s.hall_id}}</td><td><b>{{s.seat}}</b></td><td>{{s.assigned_at?.slice(0,16).replace('T',' ')}}</td></tr></tbody></table></div></section>
<div v-if="showSeat" class="modal-backdrop" @click.self="showSeat=false"><form class="modal-card" @submit.prevent="assignSeat"><h2 class="text-lg font-bold">Assign reserved seat</h2><div class="mt-5 grid gap-4"><label class="field"><span>Attendee ID</span><input v-model="seatForm.attendee_id" required/></label><label class="field"><span>Hall</span><select v-model="seatForm.hall_id" required><option value="">Select hall</option><option v-for="h in venue.seating.filter(x=>x.type==='reserved')" :key="h.id" :value="h.id">{{h.name}}</option></select></label><label class="field"><span>Seat</span><input v-model="seatForm.seat" required placeholder="e.g. A12"/></label></div><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" @click="showSeat=false">Cancel</button><button class="btn-primary" :disabled="busy">Assign</button></div></form></div>
</div></template>
